name: ci-dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  # Ex.: "dockerhubuser/meu-repo"
  IMAGE_NAME: ${{ secrets.DOCKERHUB_REPO }}

jobs:
  build-test-image-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true

      # (1) Restaurar dependências
      - name: Restore
        run: dotnet restore

      # (2) Compilar o projeto
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # (3) Executar testes (xUnit)
      - name: Test
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      # (4) Login no Docker Hub
      - name: Docker login (Docker Hub)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # (4) Build da imagem
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      # (5) Verificar vulnerabilidades com Trivy (falha se HIGH/CRITICAL)
      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      # (6) Publicar no Docker Hub (tag por SHA)
      - name: Push image (SHA tag)
        run: docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}

      # (6) Tag "latest" somente na main
      - name: Tag & push latest (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_NAME:${{ env.IMAGE_TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      # (opcional) Artefatos de teste
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: '**/*.trx'
